# Generated by Django 5.0.3 on 2024-03-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rnc", "0002_alter_drrnc_rnc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drrnc",
            name="rnc",
            field=models.IntegerField(null=True),
        ),
    ]
